[package]
name = "proto-derive"
authors = ["John Rexes Murro"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
convert_case = "0.1.0"